Express
seanoch/karate-kid-kickstart pull request #4
Opened 2022-02-14 18:11 UTC by seanoch

2022-02-16 15:59 UTC, dlvhdr requested changes

2022-02-16 15:59 UTC, dlvhdr commented on 4-Express/server/mychecklist_server.js
> +const express = require('express')
`my` is not a good name :) consider renaming to `todo_server.js`

2022-02-16 15:59 UTC, dlvhdr commented on 4-Express/client/scripts/communication_manager.js
> +const axios = require("axios").default;
what a beast name, maybe be more descriptive: `todos_api.js`?

2022-02-17 08:40 UTC, tombenezra requested changes

2022-02-17 08:40 UTC, tombenezra commented on 4-Express/client/scripts/communication_manager.js
> +const axios = require("axios").default;
why `.default`? use es6 imports for client code for consistency

2022-02-17 08:40 UTC, tombenezra commented on 4-Express/client/scripts/communication_manager.js
> +  axios.post(urlWithId, item).then(
return the result of `axios.post` from this function so whoever consumes this api will wait for the promise to be fullfilled and not the function itself.
e.g:
`return axios.post(...).catch(withErrorHandling)`
and the part which consumes it
`addOrUpdateItem(...).then(/*do something*/)`

2022-02-17 08:40 UTC, tombenezra commented on 4-Express/client/scripts/communication_manager.js
> +  axios.delete(urlWithId, { params: { id: id } }).then(
same here

2022-02-17 08:40 UTC, tombenezra commented on 4-Express/client/scripts/communication_manager.js
> +    }
this amazing error handling technique is repeated several times. export to a function

2022-02-17 08:40 UTC, tombenezra commented on 4-Express/client/scripts/communication_manager.js
> +    return response.data;
remember that `await` is blocking the execution so `line 31` will be delayed until the http request is resolved. 
consider returning the promise and let the consumer decide what to do with it

2022-02-17 08:40 UTC, tombenezra commented on 4-Express/client/scripts/todo_list.js
> +    let element = document.querySelector("[data-id='" + id + "']");
string interpolation can fit well here
```suggestion
    let element = document.querySelector(`[data-id='"${id}"']`);
```

2022-02-17 08:40 UTC, tombenezra commented on 4-Express/client/scripts/todo_list.js
> +  }
redundant?

2022-02-17 08:40 UTC, tombenezra commented on 4-Express/server/mychecklist_server.js
> +app.post('/:id', (req, res) => {
The REST api convention for saving new entry should accepts no parameter from the url itself. so maybe have the id passed as part of the body as well?

2022-02-17 08:40 UTC, tombenezra commented on 4-Express/server/mychecklist_server.js
> +const express = require('express')
the name of the file is a bit weird. how about `todos_service` or something similar? 
you could also split this file into `index.js` that will configure and start the server and `todos_[controller/service].js` to manage the routes

2022-02-20 08:23 UTC, tombenezra approved these changes

2022-02-20 09:29 UTC, merged